### ISSUE TITLE
ADBScreen find(img)--java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_Mat(III)J 

### ISSUE THREAD

**Issue by zutuanwang** [sikuli/sikuli#45]
sikuli jar version is 1.1.2

demo
---------------------------------------------------------------------------------------
ADBScreen adbs = ADBScreen.start();
System.out.println(adbs.getDeviceDescription());
try {
	Match telephone = adbs.find("pictures/adb/telephone.png");
	telephone.click();
	try {
		hread.sleep(2000);
	} catch (InterruptedException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
		adbs.aSwipeLeft();
	} catch (FindFailed e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
}

throw exception:
---------------------------------------------------------------------------------------
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_Mat(III)J
	at org.opencv.core.Mat.n_Mat(Native Method)
	at org.opencv.core.Mat.<init>(Mat.java:481)
	at org.sikuli.android.ADBDevice.captureDeviceScreenMat(ADBDevice.java:207)
	at org.sikuli.android.ADBDevice.captureDeviceScreen(ADBDevice.java:145)
	at org.sikuli.android.ADBDevice.captureScreen(ADBDevice.java:136)
	at org.sikuli.android.ADBScreen.capture(ADBScreen.java:152)
	at org.sikuli.android.ADBScreen.capture(ADBScreen.java:162)
	at org.sikuli.script.Region.doCheckLastSeenAndCreateFinder(Region.java:3001)
	at org.sikuli.script.Region.checkLastSeenAndCreateFinder(Region.java:2996)
	at org.sikuli.script.Region.doFind(Region.java:2925)
	at org.sikuli.script.Region.access$500(Region.java:21)
	at org.sikuli.script.Region$RepeatableFind.run(Region.java:3169)
	at org.sikuli.script.Region$Repeatable.repeat(Region.java:3125)
	at org.sikuli.script.Region.wait(Region.java:2756)
	at org.sikuli.script.Region.find(Region.java:2329)
	at andriod.TestADBDevice.main(TestADBDevice.java:15)

**Comment by RaiMan** [comment]
Wrong place here.
either
https://github.com/RaiMan/SikuliX1
or
https://answers.launchpad.net/sikuli

try to add as first line:
Screen s = new Screen() //might do the initialization
