### ISSUE TITLE
  Error: Error running instance method java.lang.NullPointerException.

### ISSUE THREAD

**Issue by sanaaa123** [sikuli/sikuli#53]
getting this error when i try to select folder using sikuli.
     Error: Error running instance method
java.lang.NullPointerException
	at org.sikuli.script.Screen.capture(Screen.java:587)
	at org.sikuli.script.Screen.capture(Screen.java:607)
	at org.sikuli.script.Region.doCheckLastSeenAndCreateFinder(Region.java:3001)
	at org.sikuli.script.Region.checkLastSeenAndCreateFinder(Region.java:2996)
	at org.sikuli.script.Region.doFind(Region.java:2945)
	at org.sikuli.script.Region.access$500(Region.java:21)
	at org.sikuli.script.Region$RepeatableFind.run(Region.java:3169)
	at org.sikuli.script.Region$Repeatable.repeat(Region.java:3125)
	at org.sikuli.script.Region.wait(Region.java:2756)
	at org.sikuli.script.Region.find(Region.java:2329)
	at org.sikuli.script.Region.getLocationFromTarget(Region.java:3238)
	at org.sikuli.script.Region.click(Region.java:3736)
	at org.sikuli.script.Region.click(Region.java:3721)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by sanaaa123** [comment]
On mac os

**Comment by RaiMan** [comment]
this project is no longer supported.

See project read-me for alternative.
